# Generated by Django 2.2.10 on 2020-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200326_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
