# Generated by Django 2.2.8 on 2020-02-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200201_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Consectetur id est at, iure itaque temporibus aliquid minima qui illo sed velit labore animi! Voluptates, delectus eaque cum quaerat itaque amet'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
