# Generated by Django 2.2.8 on 2020-02-13 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200201_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='Lorem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default='/static/img/animal.jpg', upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
